name: Java CI with Gradle

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Prepare test logging config
        run: |
          mkdir -p src/test/resources
          cat > src/test/resources/logback-test.xml <<'XML'
          <configuration>
            <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
              <encoder>
                <pattern>%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n</pattern>
              </encoder>
            </appender>
            <root level="INFO">
              <appender-ref ref="STDOUT"/>
            </root>
          </configuration>
          XML

      - name: Build and test
        run: ./gradlew clean build
        env:
          CI: true
          LOGGING_SYSTEM: none
          ORG_SPRINGFRAMEWORK_BOOT_LOGGING_LOGGINGSYSTEM: none
          SPRING_KAFKA_LISTENER_AUTO_STARTUP: "false"
          SPRING_KAFKA_CONSUMER_GROUP_ID: alter-ci
          SLACK_TOKEN: dummy
          SLACK_CHANNEL: C_TEST

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/test-results/test/**
            **/build/reports/tests/test/**
